version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
  - FREETYPE_VER: 2.10.0
    VS_GENERATOR: Visual Studio 15 2017 Win64
    BUILD_SHARED_LIBS: ON
  - FREETYPE_VER: 2.10.0
    VS_GENERATOR: Visual Studio 15 2017 Win64
    BUILD_SHARED_LIBS: OFF
install:
- cmd: >-
    cd Dependencies

    appveyor DownloadFile https://github.com/ubawurinna/freetype-windows-binaries/releases/download/v2.10.0/freetype-%FREETYPE_VER%.zip

    unzip -o freetype-%FREETYPE_VER%.zip

    mv win64 lib

    cd ../Build

    cmake -G "%VS_GENERATOR%" -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% .
build:
  parallel: true
  verbosity: minimal